### ISSUE TITLE
memcpy sample code not working

### ISSUE THREAD

**Issue by ghghadir** [OpenCAPI/libocxl#11]
I cloned the libocxl and the process was successful l. However, when I ran the sample memcpy , I got an error. I contacted Fred and he asked me to open an issue on the proble. here is ther error I get
root@zaiuslp15:~# ls
libocxl
root@zaiuslp15:~# cd libocxl
root@zaiuslp15:~/libocxl# ls
Changelog.md   Makefile        README.md  static-prototypes.pl
COPYING        Makefile.rules  sampleobj  symver.map
Doxyfile-html  Makefile.vars   samples    unittests
Doxyfile-man   obj             src        version.pl
root@zaiuslp15:~/libocxl# cd sampleobj
root@zaiuslp15:~/libocxl/sampleobj# ls
memcpy  memcpy.o-memcpy
root@zaiuslp15:~/libocxl/sampleobj# ./memcpy
AFU config = 0x0
traces reset and rearmed
WED=0x7ebed1de0fff  src=0x534c22308c0  dst=0x534c2231140 size=2048
unexpected status 0x0 for stop
AFU Status register is 80011
memcpy failed
root@zaiuslp15:~/libocxl/sampleobj#

**Comment by deece** [comment]
Thanks for letting me know. We had a race condition on checking the status of the stop element. Commit 2889b2ff7883aa0 fixes this by waiting for a status update before verifying it.

**Comment by ghghadir** [comment]
Thanks for taking care of it
