### ISSUE TITLE
Build error on RedHat 7.6 ppc64le

### ISSUE THREAD

**Issue by ArpadKosztolanyi** [OpenCAPI/libocxl#20]
On RedHat 7.6 building the library with make results in the following warning/errors:

[root@aiac922 libocxl]# make
VERSION_MAJOR=1 VERSION_MINOR=1 \
VERSION_PATCH=0 CC="gcc" CFLAGS="-g -Wall -Wextra -O2 -m64 -std=c11 -DLIBOCXL_SUPPRESS_INACCESSIBLE_WARNINGS -I src/include -I kernel/include -fPIC -D_FILE_OFFSET_BITS=64" \
./version.pl > src/libocxl_info.h
mkdir obj
	[CC]	 obj/afu.o
	[CC]	 obj/internal.o
	[CC]	 obj/irq.o
	[CC]	 obj/mmio.o
src/mmio.c: In function 'ocxl_mmio_read32':
src/mmio.c:639:3: warning: implicit declaration of function 'be32toh' [-Wimplicit-function-declaration]
   *out = be32toh(val);
   ^
src/mmio.c:643:3: warning: implicit declaration of function 'le32toh' [-Wimplicit-function-declaration]
   *out = le32toh(val);
   ^
src/mmio.c: In function 'ocxl_mmio_read64':
src/mmio.c:683:3: warning: implicit declaration of function 'be64toh' [-Wimplicit-function-declaration]
   *out = be64toh(val);
   ^
src/mmio.c:687:3: warning: implicit declaration of function 'le64toh' [-Wimplicit-function-declaration]
   *out = le64toh(val);
   ^
src/mmio.c: In function 'ocxl_mmio_write32':
src/mmio.c:720:3: warning: implicit declaration of function 'htobe32' [-Wimplicit-function-declaration]
   value = htobe32(value);
   ^
src/mmio.c:724:3: warning: implicit declaration of function 'htole32' [-Wimplicit-function-declaration]
   value = htole32(value);
   ^
src/mmio.c: In function 'ocxl_mmio_write64':
src/mmio.c:755:3: warning: implicit declaration of function 'htobe64' [-Wimplicit-function-declaration]
   value = htobe64(value);
   ^
src/mmio.c:759:3: warning: implicit declaration of function 'htole64' [-Wimplicit-function-declaration]
   value = htole64(value);
   ^
	[CC]	 obj/setup.o
	[CC]	 obj/libocxl.so.1.1
ln -sf libocxl.so.1.1 obj/libocxl.so.1
ln -sf libocxl.so.1.1 obj/libocxl.so
	[AR]	 obj/libocxl.a
mkdir sampleobj
	[CC]	 sampleobj/memcpy.o-memcpy
	[CC]	 sampleobj/memcpy
obj/libocxl.a(mmio.o): In function `ocxl_mmio_read32':
/tmp/libocxl/src/mmio.c:643: undefined reference to `le32toh'
/tmp/libocxl/src/mmio.c:639: undefined reference to `be32toh'
obj/libocxl.a(mmio.o): In function `ocxl_mmio_read64':
/tmp/libocxl/src/mmio.c:687: undefined reference to `le64toh'
/tmp/libocxl/src/mmio.c:683: undefined reference to `be64toh'
obj/libocxl.a(mmio.o): In function `ocxl_mmio_write32':
/tmp/libocxl/src/mmio.c:724: undefined reference to `htole32'
/tmp/libocxl/src/mmio.c:720: undefined reference to `htobe32'
obj/libocxl.a(mmio.o): In function `ocxl_mmio_write64':
/tmp/libocxl/src/mmio.c:759: undefined reference to `htole64'
/tmp/libocxl/src/mmio.c:755: undefined reference to `htobe64'
collect2: error: ld returned 1 exit status
make: *** [sampleobj/memcpy] Error 1

Adding #define _BSD_SOURCE at line 17 of src/mmio.c solves the issue.

ldd --version reports GNU libc 2.17. 

man page of endian (http://man7.org/linux/man-pages/man3/endian.3.html) says _BSD_SOURCE should be defined up to and including glibc version 2.19.

**Comment by deece** [comment]
Thanks for raising this, I have a potential fix here:
https://github.com/OpenCAPI/libocxl/tree/old-glibc

Please check out the 'old-glibc' branch from the repo and advise if this works for you.

**Comment by ArpadKosztolanyi** [comment]
The build has run sucessfully.

**Comment by deece** [comment]
Fixed in master with 36ce942f5b6e297721832cb82722a165ef3572e6
